<Project>
  <ItemGroup>
    <Compile Include="../../Content/Encounters/FirstSeverance/Rewards/RitualGrandScore.cs" Link="Domain/RitualGrandScore.cs" />
    <Compile Include="../../Content/Encounters/FirstSeverance/Rewards/RitualArmamentChoreography.cs" Link="Domain/RitualArmamentChoreography.cs" />
    <Compile Include="../../Content/Encounters/FirstSeverance/Rewards/NullCantorClawMotion.cs" Link="Domain/NullCantorClawMotion.cs" />
    <Compile Include="../../Content/Encounters/FirstSeverance/Rewards/RitualArmamentRules.cs" Link="Domain/RitualArmamentRules.cs" />
    <Compile Include="../../Content/Encounters/CrimsonFoundry/CrimsonTechnique.cs" Link="Domain/CrimsonTechnique.cs" />
  </ItemGroup>
</Project>
