// <auto-generated>
// generated by tools/export_doll_weapon_art.py; do not edit
// recipe sha256 40da38b400ea4ea7474f2032996c5b72a7cea620804ca1e638c45a4c1f75e05d
// </auto-generated>
using Vector2 = System.Numerics.Vector2;

namespace Convergence.Client.Encounters.FirstSeverance.Weapons;

/// <summary>Texel-space anchors of the exported Doll weapon art: (0, 0) is the top-left corner,
/// a texel centre is +0.5, one texel is one dot = 2 world px.</summary>
internal static class DollArtAnchors
{
    internal const string TextureRoot = "Convergence/Assets/Textures/Items/DollWeapons/";

    internal static class ClawOpen
    {
        internal const string Texture = TextureRoot + "ClawOpen";
        internal const int Width = 47;
        internal const int Height = 46;
        internal const int K = 2;
        internal static readonly Vector2 Pivot = new(0.5f, 23.03f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(38.65f, 3.92f), new(45.29f, 15.02f), new(46.41f, 28.16f), new(41.87f, 43.7f), new(27.76f, 44.83f) };
        internal static readonly Vector2[] Beads = { new(10.32f, 21.33f), new(12.83f, 21.34f), new(15.38f, 21.3f), new(10.32f, 23.92f), new(12.84f, 23.95f), new(15.37f, 23.9f) };
        internal static readonly Vector2 Grab = new(12.91f, 22.54f);
    }

    internal static class ClawOpen_L
    {
        internal const string Texture = TextureRoot + "ClawOpen_L";
        internal const int Width = 94;
        internal const int Height = 91;
        internal const int K = 1;
        internal static readonly Vector2 Pivot = new(1.5f, 45.55f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(77.31f, 7.76f), new(90.58f, 29.7f), new(92.81f, 55.7f), new(83.73f, 86.46f), new(55.52f, 88.69f) };
        internal static readonly Vector2[] Beads = { new(20.63f, 42.2f), new(25.66f, 42.22f), new(30.76f, 42.15f), new(20.65f, 47.32f), new(25.68f, 47.37f), new(30.74f, 47.28f) };
        internal static readonly Vector2 Grab = new(25.82f, 44.59f);
    }

    internal static class ClawRake
    {
        internal const string Texture = TextureRoot + "ClawRake";
        internal const int Width = 41;
        internal const int Height = 35;
        internal const int K = 2;
        internal static readonly Vector2 Pivot = new(0.5f, 17.07f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(30.21f, 2.16f), new(36.56f, 7.76f), new(40.48f, 14.63f), new(37.19f, 28.02f), new(19.03f, 33.19f) };
        internal static readonly Vector2[] Beads = { new(10.81f, 15.16f), new(13.32f, 15.17f), new(15.86f, 15.17f), new(10.81f, 17.83f), new(13.32f, 17.85f), new(15.86f, 17.83f) };
        internal static readonly Vector2 Grab = new(13.34f, 16.34f);
    }

    internal static class ClawRake_L
    {
        internal const string Texture = TextureRoot + "ClawRake_L";
        internal const int Width = 82;
        internal const int Height = 69;
        internal const int K = 1;
        internal static readonly Vector2 Pivot = new(1.5f, 33.65f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(60.42f, 4.26f), new(73.13f, 15.29f), new(80.95f, 28.84f), new(74.39f, 55.24f), new(38.07f, 65.44f) };
        internal static readonly Vector2[] Beads = { new(21.61f, 29.9f), new(26.64f, 29.9f), new(31.72f, 29.91f), new(21.61f, 35.15f), new(26.65f, 35.19f), new(31.72f, 35.14f) };
        internal static readonly Vector2 Grab = new(26.67f, 32.22f);
    }

    internal static class ClawClench
    {
        internal const string Texture = TextureRoot + "ClawClench";
        internal const int Width = 37;
        internal const int Height = 31;
        internal const int K = 2;
        internal static readonly Vector2 Pivot = new(0.5f, 16.37f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(29.89f, 3.57f), new(36.33f, 9.17f), new(34.06f, 15.89f), new(36.33f, 21.48f) };
        internal static readonly Vector2[] Beads = { new(13.33f, 14.16f), new(16.31f, 14.16f), new(19.26f, 14.16f), new(13.34f, 17.41f), new(16.32f, 17.43f), new(19.28f, 17.42f) };
        internal static readonly Vector2 Grab = new(16.21f, 15.76f);
    }

    internal static class ClawClench_L
    {
        internal const string Texture = TextureRoot + "ClawClench_L";
        internal const int Width = 73;
        internal const int Height = 61;
        internal const int K = 1;
        internal static readonly Vector2 Pivot = new(1.5f, 32.21f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(58.97f, 7.03f), new(71.67f, 18.04f), new(67.21f, 31.27f), new(71.67f, 42.27f) };
        internal static readonly Vector2[] Beads = { new(26.31f, 27.86f), new(32.19f, 27.86f), new(38f, 27.87f), new(26.31f, 34.27f), new(32.19f, 34.3f), new(38.04f, 34.29f) };
        internal static readonly Vector2 Grab = new(31.98f, 31.02f);
    }

    internal static class ClawThrust
    {
        internal const string Texture = TextureRoot + "ClawThrust";
        internal const int Width = 50;
        internal const int Height = 23;
        internal const int K = 2;
        internal static readonly Vector2 Pivot = new(0.5f, 11.57f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(49.41f, 7.19f), new(49.41f, 12.59f), new(49.27f, 17.92f), new(46.61f, 21.98f) };
        internal static readonly Vector2[] Beads = { new(12.15f, 9.41f), new(14.77f, 9.4f), new(17.39f, 9.4f), new(12.14f, 12.28f), new(14.76f, 12.28f), new(17.39f, 12.27f) };
        internal static readonly Vector2 Grab = new(14.85f, 10.92f);
    }

    internal static class ClawThrust_L
    {
        internal const string Texture = TextureRoot + "ClawThrust_L";
        internal const int Width = 100;
        internal const int Height = 46;
        internal const int K = 1;
        internal static readonly Vector2 Pivot = new(1.5f, 23.14f);
        // Ordered by angle around Pivot (topmost first); an index is not a finger, and a pose can show fewer than 5 tips.
        internal static readonly Vector2[] Tips = { new(98.81f, 14.38f), new(98.81f, 25.17f), new(98.53f, 35.83f), new(93.23f, 43.97f) };
        internal static readonly Vector2[] Beads = { new(24.29f, 18.81f), new(29.54f, 18.8f), new(34.78f, 18.81f), new(24.29f, 24.56f), new(29.53f, 24.57f), new(34.79f, 24.54f) };
        internal static readonly Vector2 Grab = new(29.71f, 21.85f);
    }

    internal static class NullRefrainIcon
    {
        internal const string Texture = TextureRoot + "NullRefrainIcon";
        internal const int Width = 62;
        internal const int Height = 40;
        internal const int StoredScale = 2;
    }

    internal static class MeridianGun
    {
        internal const string Texture = TextureRoot + "MeridianGun";
        internal const int Width = 87;
        internal const int Height = 17;
        internal const int K = 3;
        internal static readonly Vector2 Muzzle = new(87f, 9f);
        internal static readonly Vector2 Grip = new(15.05f, 15.26f);
        internal static readonly Vector2 KeySeat = new(11.5f, 4f);
        internal static readonly Vector2[] Seats = { new(23f, 6f), new(36f, 6f), new(22f, 0f), new(10f, 3f) };
    }

    internal static class MeridianBare
    {
        internal const string Texture = TextureRoot + "MeridianBare";
        internal const int Width = 87;
        internal const int Height = 17;
        internal const int K = 3;
        internal static readonly Vector2 Muzzle = new(87f, 9f);
        internal static readonly Vector2 Grip = new(15.05f, 15.26f);
        internal static readonly Vector2 KeySeat = new(11.5f, 4f);
        internal static readonly Vector2[] Seats = { new(23f, 6f), new(36f, 6f), new(22f, 0f), new(10f, 3f) };
    }

    internal static class MeridianParts
    {
        internal const string Texture = TextureRoot + "MeridianParts";
        internal const int Width = 188;
        internal const int Height = 6;
        internal const int K = 3;
        internal const int FrameWidth = 47;
        internal const int FrameHeight = 6;
        internal static readonly Vector2[] Seats = { new(23f, 6f), new(36f, 6f), new(22f, 0f), new(10f, 3f) };
        internal static readonly string[] Parts = { "cylinder", "shroud", "sight", "spring_housing" };
    }

    internal static class MeridianKey
    {
        internal const string Texture = TextureRoot + "MeridianKey";
        internal const int Width = 144;
        internal const int Height = 30;
        internal const int K = 1;
        internal const int FrameWidth = 36;
        internal const int FrameHeight = 30;
        internal static readonly Vector2 ShaftBottom = new(18f, 30f);
    }

    internal static class PaleMeridianIcon
    {
        internal const string Texture = TextureRoot + "PaleMeridianIcon";
        internal const int Width = 56;
        internal const int Height = 40;
        internal const int StoredScale = 2;
    }

    internal static class LacunaBook
    {
        internal const string Texture = TextureRoot + "LacunaBook";
        internal const int Width = 42;
        internal const int Height = 55;
        internal const int K = 1;
        internal static readonly Vector2 Hole = new(18.94f, 25.94f);
        internal const float HoleRadius = 5.96f;
        internal static readonly Vector2 Clasp = new(35.25f, 26.98f);
    }

    internal static class LacunaBook_S
    {
        internal const string Texture = TextureRoot + "LacunaBook_S";
        internal const int Width = 21;
        internal const int Height = 28;
        internal const int K = 2;
        internal static readonly Vector2 Hole = new(9.47f, 13.21f);
        internal const float HoleRadius = 2.98f;
        internal static readonly Vector2 Clasp = new(17.63f, 13.74f);
    }

    internal static class LacunaTestamentIcon
    {
        internal const string Texture = TextureRoot + "LacunaTestamentIcon";
        internal const int Width = 34;
        internal const int Height = 46;
        internal const int StoredScale = 2;
    }

    internal static class LacunaIris
    {
        internal const string Texture = TextureRoot + "LacunaIris";
        internal const int Width = 100;
        internal const int Height = 25;
        internal const int K = 2;
        internal const int FrameWidth = 25;
        internal const int FrameHeight = 25;
        internal static readonly Vector2 Centre = new(12.53f, 12.5f);
        internal const float RingRadius = 10.32f;
        internal static readonly float[] ApertureRadii = { 0f, 1.82f, 4.66f, 7.46f };
    }

    internal static class LacunaGreatIris
    {
        internal const string Texture = TextureRoot + "LacunaGreatIris";
        internal const int Width = 78;
        internal const int Height = 80;
        internal const int K = 1;
        internal static readonly Vector2 Centre = new(39.06f, 40.23f);
        internal const float RingRadius = 33.8f;
        internal static readonly Vector2 Hole = new(39.06f, 40.04f);
        internal const float HoleRadius = 20.89f;
        internal const float OuterRadius = 38.93f;
    }

    internal static class Chorister0
    {
        internal const string Texture = TextureRoot + "Chorister0";
        internal const int Width = 66;
        internal const int Height = 38;
        internal const int K = 2;
        internal const int FrameWidth = 22;
        internal const int FrameHeight = 38;
        internal static readonly Vector2 StandTip = new(10.5f, 38f);
        internal static readonly Vector2[] Mouths = { new(14.8f, 15.34f), new(14.78f, 15.27f), new(15.65f, 12.81f) };
    }

    internal static class Chorister1
    {
        internal const string Texture = TextureRoot + "Chorister1";
        internal const int Width = 66;
        internal const int Height = 38;
        internal const int K = 2;
        internal const int FrameWidth = 22;
        internal const int FrameHeight = 38;
        internal static readonly Vector2 StandTip = new(10.5f, 38f);
        internal static readonly Vector2[] Mouths = { new(14.86f, 14.51f), new(15.11f, 14.51f), new(15.92f, 12.43f) };
    }

    internal static class Chorister2
    {
        internal const string Texture = TextureRoot + "Chorister2";
        internal const int Width = 66;
        internal const int Height = 38;
        internal const int K = 2;
        internal const int FrameWidth = 22;
        internal const int FrameHeight = 38;
        internal static readonly Vector2 StandTip = new(10.5f, 38f);
        internal static readonly Vector2[] Mouths = { new(13.34f, 15.19f), new(14.79f, 16.17f), new(13.97f, 13.24f) };
    }

    internal static class ChoirOrgan
    {
        internal const string Texture = TextureRoot + "ChoirOrgan";
        internal const int Width = 95;
        internal const int Height = 96;
        internal const int K = 1;
        internal static readonly Vector2 Mouth = new(47.56f, 73.71f);
        internal const float MouthRadius = 9.24f;
        internal const int CaseTopRow = 31;
        internal const int PipeTopRow = 0;
    }

    internal static class ChoirBaton
    {
        internal const string Texture = TextureRoot + "ChoirBaton";
        internal const int Width = 27;
        internal const int Height = 28;
        internal const int K = 2;
        internal static readonly Vector2 Pommel = new(2.55f, 24.67f);
        internal static readonly Vector2 Grip = new(10.1f, 17.49f);
        internal static readonly Vector2 Tip = new(26.5f, 0.5f);
    }

    internal static class ChoirOfTheUnmadeIcon
    {
        internal const string Texture = TextureRoot + "ChoirOfTheUnmadeIcon";
        internal const int Width = 54;
        internal const int Height = 56;
        internal const int StoredScale = 2;
    }

    internal static class ChoirOfTheUnmadeBuff
    {
        internal const string Texture = TextureRoot + "ChoirOfTheUnmadeBuff";
        internal const int Width = 32;
        internal const int Height = 32;
        internal const int StoredScale = 2;
    }

    internal static class WitnessBlade
    {
        internal const string Texture = TextureRoot + "WitnessBlade";
        internal const int Width = 65;
        internal const int Height = 12;
        internal const int K = 2;
        internal static readonly Vector2 Eye = new(18.45f, 6.49f);
        internal const float EyeRadius = 1.17f;
        internal static readonly Vector2 Tip = new(65f, 5.5f);
        internal static readonly Vector2 Pommel = new(0f, 5.5f);
        internal static readonly Vector2 Pivot = new(33.45f, 6.25f);
        internal const float GuardX0 = 12.7f;
        internal const float GuardX1 = 14.88f;
        internal static readonly Vector2 Guard = new(14.06f, 5.97f);
    }

    internal static class WitnessBlade_L
    {
        internal const string Texture = TextureRoot + "WitnessBlade_L";
        internal const int Width = 130;
        internal const int Height = 23;
        internal const int K = 1;
        internal static readonly Vector2 Eye = new(36.89f, 12.45f);
        internal const float EyeRadius = 2.35f;
        internal static readonly Vector2 Tip = new(130f, 10.5f);
        internal static readonly Vector2 Pommel = new(0f, 11.5f);
        internal static readonly Vector2 Pivot = new(67.32f, 12.11f);
        internal const float GuardX0 = 25.41f;
        internal const float GuardX1 = 29.76f;
        internal static readonly Vector2 Guard = new(28.13f, 11.45f);
    }

    internal static class WitnessSword
    {
        internal const string Texture = TextureRoot + "WitnessSword";
        internal const int Width = 9;
        internal const int Height = 53;
        internal const int K = 2;
        internal static readonly Vector2 StakePoint = new(4.5f, 53f);
        internal static readonly Vector2 Pommel = new(4.5f, 0f);
        internal static readonly Vector2 Guard = new(4.5f, 8.5f);
        internal const int GuardRow = 8;
    }

    internal static class WitnessShards
    {
        internal const string Texture = TextureRoot + "WitnessShards";
        internal const int Width = 48;
        internal const int Height = 10;
        internal const int K = 2;
        internal const int FrameWidth = 16;
        internal const int FrameHeight = 10;
        internal static readonly Vector2 Pivot = new(6.57f, 5.73f);
        internal static readonly Vector2[] Points = { new(16f, 6.5f), new(16f, 6.5f), new(16f, 6.5f) };
    }

    internal static class LastWitnessIcon
    {
        internal const string Texture = TextureRoot + "LastWitnessIcon";
        internal const int Width = 60;
        internal const int Height = 62;
        internal const int StoredScale = 2;
    }
}
