"""Doll weapon art exporter (tools/export_doll_weapon_art.py) contracts.

The source contracts use only the standard library and always run. The synthetic
tests need numpy, scipy and Pillow (local asset tools, not in CI requirements) and
skip without them. The dry-run test also needs the external delivery folder
(asset-deliveries/doll-weapons/2026-10-02 next to a parent of the repository, or
$CONVERGENCE_DOLL_WEAPON_DELIVERY) and skips when it is absent.
"""
import ast
import json
import math
import os
from pathlib import Path
import re
import sys
import tempfile
import types
import unittest
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
EXPORTER = ROOT / "tools" / "export_doll_weapon_art.py"
BRIEF_PALETTE = ["#121017", "#1d1a22", "#302a29", "#49404a", "#9c8070", "#d0b69e", "#f4e3ce", "#fcf4e6",
                 "#c9c4c9", "#e1dce0", "#684828", "#a07b48", "#d5b279", "#301840", "#8c141c", "#4c040c"]
# personal absolute paths (built from pieces so this file does not match itself)
INK_BOUNDARY_FLOOR = 0.85  # outer-boundary ink share of every k <= 3 sprite (the weakest today is MeridianGun at 0.893)
PERSONAL_PATH = re.compile("|".join((r"[A-Za-z]:[\\/](?:Users|Workspace)", "/" + "home/", "/" + "Users/")))

try:
    import numpy as np
    import scipy  # noqa: F401
    from PIL import Image
    sys.path.insert(0, str(ROOT / "tools"))
    import export_doll_weapon_art as ex
    HAVE_TOOLS = True
except ImportError:  # CI installs only PyYAML
    HAVE_TOOLS = False


def module_value(name):
    tree = ast.parse(EXPORTER.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            return node.value
    raise AssertionError(f"{name} not found")


class ExporterSourceContracts(unittest.TestCase):
    def test_inputs_are_pinned_by_full_sha256(self):
        inputs = ast.literal_eval(module_value("INPUTS"))
        self.assertEqual(21, len(inputs))
        for file, digest in inputs.items():
            self.assertRegex(file, r"^alpha/DW0[1-5][A-Z0-9]*_[a-d]\.png$")
            self.assertRegex(digest, r"^[0-9a-f]{64}$")
        source = EXPORTER.read_text(encoding="utf-8")
        for file in re.findall(r'Sheet\("(alpha/[^"]+)"', source):
            self.assertIn(file, inputs)

    def test_palette_is_the_brief_palette(self):
        palette = ast.literal_eval(module_value("PALETTE"))
        self.assertEqual(BRIEF_PALETTE, [hex_ for _, hex_ in palette])

    def test_default_output_is_local_and_the_repo_paths_are_the_agreed_ones(self):
        # what writing into the repository does is tested functionally (WriteOutputsTests, dry-run tests)
        source = EXPORTER.read_text(encoding="utf-8")
        self.assertIn('PREVIEW_DIR = ROOT / ".local" / "doll-weapon-art"', source)
        self.assertIn('TEXTURE_REL = Path("Assets") / "Textures" / "Items" / "DollWeapons"', source)
        self.assertIn('ANCHORS_REL = Path("Client") / "Encounters" / "FirstSeverance" / "Weapons" / "DollArtAnchors.g.cs"', source)
        self.assertIn('GENERATED_HEADER = "generated by tools/export_doll_weapon_art.py; do not edit"', source)
        self.assertIn('"--write-repo", action="store_true"', source)
        self.assertIn('"--only", nargs="+"', source)
        # the dry-run copy of the anchors is not a .cs file the Mod build could pick up from .local
        self.assertIn('"DollArtAnchors.g.cs.txt"', source)

    def test_reuses_the_unmodified_ebon_helpers_and_commits_no_personal_paths(self):
        source = EXPORTER.read_text(encoding="utf-8")
        self.assertIn("from export_ebon_art import block_mode, clean_alpha, sha256", source)
        for path in (EXPORTER, Path(__file__)):
            self.assertIsNone(PERSONAL_PATH.search(path.read_text(encoding="utf-8")), path.name)


@unittest.skipUnless(HAVE_TOOLS, "numpy, scipy and Pillow are local asset-tool dependencies")
class SyntheticExportTests(unittest.TestCase):
    INK, IRON0, IRON1, P2, P3, PEARL1, BRASS0, BRASS1, GLASS = 0, 1, 2, 6, 7, 9, 10, 11, 13

    @staticmethod
    def draw(dots, pitch, margin=16):
        """Dot-level palette indices (-1 transparent) -> RGBA at `pitch` px per dot (nearest)."""
        dots = np.asarray(dots)
        h, w = dots.shape
        size = (int(round(h * pitch)) + 2 * margin, int(round(w * pitch)) + 2 * margin)
        rgba = np.zeros(size + (4,), dtype=np.uint8)
        ys = np.floor((np.arange(size[0]) - margin) / pitch).astype(int)
        xs = np.floor((np.arange(size[1]) - margin) / pitch).astype(int)
        inside = (ys[:, None] >= 0) & (ys[:, None] < h) & (xs[None, :] >= 0) & (xs[None, :] < w)
        source = dots[np.clip(ys, 0, h - 1)[:, None], np.clip(xs, 0, w - 1)[None, :]]
        opaque = inside & (source >= 0)
        rgba[opaque, :3] = ex.PALETTE_RGB[source[opaque]]
        rgba[opaque, 3] = 255
        return rgba

    @staticmethod
    def outlined(dots, region, fill):
        """Fill a boolean dot region and give it a one-dot ink outline outside it."""
        dots[region] = fill
        ring = ex.ndimage.binary_dilation(region, structure=ex.EIGHT) & ~region & (dots < 0)
        dots[ring] = 0

    def test_pitch_recovers_jittered_grids(self):
        for pitch in (7, 9.5, 12, 14.4, 20):
            for seed in range(3):
                rng = np.random.default_rng(seed)
                count = 44

                def bounds():
                    b = np.arange(count + 1) * pitch + rng.uniform(-0.01, 0.01, count + 1) * pitch
                    return np.round(b - b[0]).astype(int) + 8

                bx, by = bounds(), bounds()
                image = np.zeros((by[-1] + 8, bx[-1] + 8, 4), dtype=np.uint8)
                tones = rng.integers(0, len(ex.PALETTE), (count, count))
                for j in range(count):
                    for i in range(count):
                        image[by[j]:by[j + 1], bx[i]:bx[i + 1], :3] = ex.PALETTE_RGB[tones[j, i]]
                        image[by[j]:by[j + 1], bx[i]:bx[i + 1], 3] = 255
                record, used = ex.measure_pitch([image])
                with self.subTest(pitch=pitch, seed=seed):
                    self.assertAlmostEqual(pitch, used, delta=0.05)
                    self.assertGreater(record["coherence"], 0.5)
                    self.assertFalse(record["at_search_ceiling"])

    @staticmethod
    def block_grid(pitch, block, count=44, seed=0):
        """An exact (unjittered) grid of `count` dots at `pitch` px whose tones are constant over
        block x block dots; neighbouring blocks differ, so every block edge is a drawn edge."""
        rng = np.random.default_rng(seed)
        n = count // block
        tones = rng.integers(0, len(ex.PALETTE), (n, n))
        for j in range(n):
            for i in range(n):
                while (i and tones[j, i] == tones[j, i - 1]) or (j and tones[j, i] == tones[j - 1, i]):
                    tones[j, i] = rng.integers(0, len(ex.PALETTE))
        step = pitch * block
        edges = np.round(np.arange(n + 1) * step).astype(int) + 8
        image = np.zeros((edges[-1] + 8, edges[-1] + 8, 4), dtype=np.uint8)
        for j in range(n):
            for i in range(n):
                image[edges[j]:edges[j + 1], edges[i]:edges[i + 1], :3] = ex.PALETTE_RGB[tones[j, i]]
                image[edges[j]:edges[j + 1], edges[i]:edges[i + 1], 3] = 255
        return image

    def test_pitch_search_range_is_3_to_24_px(self):
        self.assertEqual((3.0, 24.0), (float(ex.PERIODS[0]), float(ex.PERIODS[-1])))

    def test_sub_harmonic_lift_takes_the_period_the_edges_really_have(self):
        # On an exact grid the half and third periods are as coherent as the fundamental, and the
        # smallest of them wins the first search; the lift must move to the largest coherent multiple.
        for pitch, block, expected, from_px in ((8.0, 1, 8.0, 4.0), (7.0, 1, 7.0, 3.5),
                                                (6.0, 2, 12.0, 3.0), (7.0, 2, 14.0, 3.5), (5.0, 2, 10.0, 5.0)):
            record, used = ex.measure_pitch([self.block_grid(pitch, block)])
            with self.subTest(pitch=pitch, block=block):
                self.assertAlmostEqual(expected, used, delta=0.05)
                self.assertEqual(from_px, record["lifted_from_px"])
                self.assertGreater(record["coherence"], 0.95)
        # a grid whose fundamental already wins the first search is not lifted
        rng = np.random.default_rng(0)
        bounds = np.round(np.arange(45) * 9.5 + rng.uniform(-0.095, 0.095, 45)).astype(int) + 8
        image = np.zeros((bounds[-1] + 8, bounds[-1] + 8, 4), dtype=np.uint8)
        tones = rng.integers(0, len(ex.PALETTE), (44, 44))
        for j in range(44):
            for i in range(44):
                image[bounds[j]:bounds[j + 1], bounds[i]:bounds[i + 1], :3] = ex.PALETTE_RGB[tones[j, i]]
                image[bounds[j]:bounds[j + 1], bounds[i]:bounds[i + 1], 3] = 255
        record, used = ex.measure_pitch([image])
        self.assertIsNone(record["lifted_from_px"])
        self.assertAlmostEqual(9.5, used, delta=0.05)

    def test_palette_snap_is_exact_and_deterministic(self):
        palette = np.zeros((1, len(ex.PALETTE), 4), dtype=np.uint8)
        palette[0, :, :3], palette[0, :, 3] = ex.PALETTE_RGB, 255
        idx, de = ex.snap(palette)
        self.assertEqual(list(range(len(ex.PALETTE))), idx[0].tolist())
        self.assertLess(float(np.nanmax(de)), 1e-6)
        rng = np.random.default_rng(7)
        noise = rng.integers(0, 256, (48, 64, 4), dtype=np.uint8)
        first, second = ex.snap(noise), ex.snap(noise.copy())
        self.assertTrue(np.array_equal(first[0], second[0]))
        self.assertTrue(np.array_equal(first[1], second[1], equal_nan=True))
        black = np.array([[[8, 8, 8, 255]]], dtype=np.uint8)
        self.assertEqual(self.INK, int(ex.snap(black)[0][0, 0]))
        transparent = np.zeros((1, 1, 4), dtype=np.uint8)
        self.assertEqual(-1, int(ex.snap(transparent)[0][0, 0]))

    def test_reduction_keeps_the_ink_outline_at_k2_and_k3(self):
        yy, xx = np.mgrid[0:60, 0:72]
        body = ((xx - 36) / 30.0) ** 2 + ((yy - 30) / 24.0) ** 2 <= 1.0
        body |= (xx > 40) & (xx < 70) & (yy > 23) & (yy < 37)
        dots = np.full(body.shape, -1, dtype=np.int16)
        self.outlined(dots, ex.ndimage.binary_erosion(body), self.P2)
        dots[(yy > 20) & (yy < 28) & (xx > 20) & (xx < 34)] = self.BRASS1
        pitch = 8.0
        objects, *_ = ex.prepare_objects(self.draw(dots, pitch), (1, 1), 1)
        obj = objects[0]
        for k in (2, 3):
            texels, stats = ex.reduce_cells(obj.idx, ex.object_grid(obj.size, pitch, k), pitch * pitch)
            with self.subTest(k=k):
                self.assertGreaterEqual(stats["ink_boundary_share"], 0.95)
                self.assertGreater((texels == self.P2).sum(), 0)

    def claw_hand(self, finger_rows):
        """A cuffed hand with a six-bead brass plate and one talon per finger row; returns the palette indices."""
        h, w = 42, 64
        yy, xx = np.mgrid[0:h, 0:w]
        dots = np.full((h, w), -1, dtype=np.int16)
        self.outlined(dots, (xx >= 1) & (xx <= 5) & (yy >= 12) & (yy <= 27), self.IRON1)
        dots[(xx >= 6) & (xx <= 7) & (yy >= 11) & (yy <= 28)] = self.BRASS1
        palm = (xx >= 8) & (xx <= 36) & (yy >= 7) & (yy <= 32)
        for row in finger_rows:
            palm |= (xx >= 36) & (xx <= 54 + (row % 5)) & (yy >= row) & (yy <= row + 2)
        self.outlined(dots, palm, self.P2)
        plate = (xx >= 13) & (xx <= 27) & (yy >= 14) & (yy <= 25)
        dots[plate] = self.BRASS1
        for row in range(2):
            for col in range(3):
                y0, x0 = 16 + row * 5, 15 + col * 4
                dots[y0:y0 + 2, x0:x0 + 2] = self.GLASS
                dots[y0, x0] = self.PEARL1
        objects, *_ = ex.prepare_objects(self.draw(dots, 7.0), (1, 1), 1)
        return objects[0].idx

    def test_six_bead_plate_yields_six_ordered_beads(self):
        pitch = 7.0
        found, notes = ex.claw_anchors(self.claw_hand((9, 15, 21, 27, 33)), pitch)
        self.assertEqual([], notes)
        beads = found["beads"]
        self.assertEqual(6, len(beads))
        top, bottom = beads[:3], beads[3:]
        self.assertLess(max(b[1] for b in top) + 2 * pitch, min(b[1] for b in bottom))
        for row in (top, bottom):
            self.assertEqual(sorted(b[0] for b in row), [b[0] for b in row])
        self.assertLess(found["pivot"][0], 2 * pitch)
        self.assertEqual(ex.TALONS, len(found["tips"]))
        # the tips are ordered by angle around the pivot (image coordinates, y down): topmost first
        pivot = found["pivot"]
        angles = [math.atan2(t[1] - pivot[1], t[0] - pivot[0]) for t in found["tips"]]
        self.assertEqual(sorted(angles), angles)
        self.assertLess(found["tips"][0][1], found["tips"][-1][1])

    def test_a_hand_with_fewer_than_five_tips_is_reported(self):
        found, notes = ex.claw_anchors(self.claw_hand((9, 15, 21, 27)), 7.0)
        self.assertEqual(4, len(found["tips"]))
        self.assertEqual(1, len([n for n in notes if "talon tips" in n and "not a fixed finger" in n]), notes)
        self.assertIn("found 4 talon tips, expected 5", notes[0])

    def test_ring_yields_the_hole_centre_and_radius(self):
        size, cx, cy = 200, 97.3, 104.6
        yy, xx = np.mgrid[0:size, 0:size] + 0.5
        distance = np.hypot(xx - cx, yy - cy)
        ring = (distance <= 70) & (distance >= 38)
        holes = ex.enclosed_holes(ring, 16)
        self.assertEqual(1, len(holes))
        area, centre, _, _ = holes[0]
        self.assertAlmostEqual(cx, centre[0], delta=0.5)
        self.assertAlmostEqual(cy, centre[1], delta=0.5)
        self.assertAlmostEqual(38.0, math.sqrt(area / math.pi), delta=0.8)
        fitted, radius = ex.fit_circle(ring & (distance >= 64))
        self.assertAlmostEqual(cx, fitted[0], delta=0.5)
        self.assertAlmostEqual(cy, fitted[1], delta=0.5)
        self.assertAlmostEqual(67.0, radius, delta=1.5)

    def gun_pair(self):
        h, w = 26, 72
        yy, xx = np.mgrid[0:h, 0:w]
        base = np.full((h, w), -1, dtype=np.int16)
        body = ((xx >= 2) & (xx <= 33) & (yy >= 11) & (yy <= 17)) | ((xx >= 15) & (xx <= 19) & (yy >= 17) & (yy <= 22))
        self.outlined(base, body, self.IRON1)
        self.outlined(base, (xx >= 34) & (xx <= 68) & (yy >= 13) & (yy <= 14), self.P2)
        bare = base.copy()
        # parts: cylinder over the receiver, a shroud on the barrel, a ring sight, a rear housing with a stub
        cylinder = (xx >= 20) & (xx <= 30) & (yy >= 10) & (yy <= 16)
        shroud = (xx >= 37) & (xx <= 64) & (yy >= 10) & (yy <= 11)
        ring = np.hypot(xx - 25, yy - 4.0)
        sight = ((ring <= 3.9) & (ring >= 1.7)) | ((xx == 25) & (yy == 8))  # an ink row parts it from the cylinder
        housing = ((xx >= 6) & (xx <= 11) & (yy >= 7) & (yy <= 10)) | ((xx >= 8) & (xx <= 9) & (yy >= 4) & (yy <= 6))
        for region in (cylinder, shroud, sight, housing):
            base[region] = self.BRASS1
            outline = ex.ndimage.binary_dilation(region, structure=ex.EIGHT) & ~ex.ndimage.binary_fill_holes(region)
            base[outline & ~((base == self.BRASS1) | (base == self.P2))] = self.INK
        # the bare gun: an outlined dark recess where the cylinder sat, a dark block for the
        # housing, nothing for the sight and the shroud
        bare[ex.ndimage.binary_dilation(cylinder, structure=ex.EIGHT) & ~cylinder] = self.INK
        bare[cylinder] = self.IRON0
        bare[(xx >= 6) & (xx <= 11) & (yy >= 9) & (yy <= 10)] = self.IRON0
        bare[(xx >= 5) & (xx <= 12) & (yy == 8)] = self.INK
        return base, bare

    def test_shifted_gun_pair_yields_four_labelled_parts(self):
        base_dots, bare_dots = self.gun_pair()
        pitch = 6
        base, bare = self.draw(base_dots, pitch, 40), self.draw(bare_dots, pitch, 40)
        bare = ex.shifted(bare, -6, -6, 0)  # the edit drifted by (-6, -6); registration must undo it
        idx, _ = ex.snap(base)
        parts, registration, notes = ex.cut_gun_parts(base, idx, bare, float(pitch), float(pitch))
        self.assertEqual([6, 6], registration["shift"])
        self.assertEqual(set(ex.PART_ORDER), set(parts), notes)
        self.assertTrue(all(not n.startswith("parts cut") for n in notes), notes)
        self.assertGreater(parts["sight"]["hole_area"], 0)
        self.assertGreaterEqual(parts["shroud"]["aspect"], 4)
        self.assertLess(parts["spring_housing"]["box"][0], parts["cylinder"]["box"][0])
        # the stub on the housing comes with it (the key seat stands there)
        self.assertLessEqual(parts["spring_housing"]["box"][1], 40 + 4 * pitch + 1)

    def test_key_frames_align_on_the_shaft(self):
        pitch, cell = 8, (24, 20)
        sheet = np.full((cell[1] * 2, cell[0] * 2), -1, dtype=np.int16)
        lobes = (11, 7, 1, 7)
        offsets = ((3, 2), (9, 4), (5, 1), (7, 3))
        for frame, (half, (ox, oy)) in enumerate(zip(lobes, offsets)):
            cx, cy = (frame % 2) * cell[0] + ox, (frame // 2) * cell[1] + oy
            shaft_x = cx + 6
            sheet[cy + 7:cy + 13, shaft_x:shaft_x + 2] = self.BRASS1
            left = shaft_x + 1 - half // 2 - 1
            sheet[cy + 1:cy + 7, max(cx, left):shaft_x + 1 + half // 2 + 1] = self.BRASS1
            sheet[cy + 12, shaft_x:shaft_x + 2] = self.BRASS0
        objects, *_ = ex.prepare_objects(self.draw(sheet, pitch, 0), (2, 2), 4)
        frames, anchors = [], []
        for obj in objects:
            texels, _ = ex.reduce_cells(obj.idx, ex.object_grid(obj.size, pitch, 1), pitch * pitch)
            texels, _ = ex.trim(texels)
            frames.append(texels)
            anchors.append(ex.texel_extreme(texels, "bottom"))
        strip, meta = ex.strip(frames, anchors)
        width = meta["frame_size"][0]
        for i in range(4):
            frame = strip[:, i * width:(i + 1) * width]
            with self.subTest(frame=i):
                bottom = ex.texel_extreme(frame, "bottom")
                self.assertEqual(meta["anchor"][1], bottom[1])
                self.assertAlmostEqual(meta["anchor"][0], bottom[0], delta=0.5)

    def test_same_inputs_produce_identical_bytes(self):
        yy, xx = np.mgrid[0:30, 0:40]
        dots = np.full((30, 40), -1, dtype=np.int16)
        self.outlined(dots, (np.hypot(xx - 20, yy - 15) <= 11), self.P3)
        dots[(np.hypot(xx - 20, yy - 15) <= 4)] = self.BRASS1

        def run():
            objects, *_ = ex.prepare_objects(self.draw(dots, 9.0), (1, 1), 1)
            obj = objects[0]
            texels, stats = ex.reduce_cells(obj.idx, ex.object_grid(obj.size, 9.0, 2), 81.0)
            texels, offset = ex.trim(texels)
            output = ex.Output("Probe", texels, {"k": 2, "png_size": [texels.shape[1], texels.shape[0]],
                                                 "world_px": [2 * texels.shape[1], 2 * texels.shape[0]]},
                               {"centre": ex.texel_centroid(texels), "radius": 1.5})
            with tempfile.TemporaryDirectory() as folder:
                sheet = Path(folder) / "contact.png"
                ex.contact_sheet([output], sheet)
                contact = sheet.read_bytes()
            return (ex.png_bytes(output.stored()), ex.anchors_cs([output], "0" * 64),
                    json.dumps(stats, sort_keys=True), contact)

        self.assertEqual(run(), run())


def written_files(root):
    return sorted(p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file())


@unittest.skipUnless(HAVE_TOOLS, "numpy, scipy and Pillow are local asset-tool dependencies")
class WriteOutputsTests(unittest.TestCase):
    """What write_outputs puts where: the preview folder always, the repository only with write_repo."""
    REPO_PNG = "Assets/Textures/Items/DollWeapons/"
    ANCHORS = "Client/Encounters/FirstSeverance/Weapons/DollArtAnchors.g.cs"

    @staticmethod
    def fake_exporter():
        def output(name, runtime=True):
            texels = np.full((6, 8), -1, dtype=np.int16)
            texels[1:5, 1:7] = 6
            texels[1:5, 1] = 0
            info = {"k": 2, "png_size": [8, 6], "world_px": [16, 12]}
            return ex.Output(name, texels, info, {"centre": [4.0, 3.0]}, runtime=runtime)

        outputs = [output("Alpha"), output("Alpha_L"), output("Beta"), output("AlphaCheck", runtime=False)]
        return types.SimpleNamespace(outputs=outputs, report={"recipe_sha256": "0" * 64, "outputs": {}})

    def test_a_default_run_writes_only_the_preview_folder(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            ex.write_outputs(self.fake_exporter(), root / "preview", root=root)
            written = written_files(root)
            self.assertEqual([], [w for w in written if not w.startswith("preview/")])
            for name in ("Alpha.png", "Alpha_L.png", "Beta.png", "AlphaCheck.png", "report.json", "contact.png",
                         "anchors.png", "DollArtAnchors.g.cs.txt"):
                self.assertIn("preview/" + name, written)
            self.assertFalse((root / "Assets").exists())
            self.assertFalse((root / "Client").exists())

    def test_write_repo_adds_the_runtime_pngs_and_the_anchors(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            ex.write_outputs(self.fake_exporter(), root / "preview", write_repo=True, root=root)
            repo = [w for w in written_files(root) if not w.startswith("preview/")]
            # the preview-only output is never a runtime asset
            self.assertEqual(sorted([self.REPO_PNG + "Alpha.png", self.REPO_PNG + "Alpha_L.png", self.REPO_PNG + "Beta.png",
                                     self.ANCHORS]), repo)
            self.assertEqual((root / "preview" / "Alpha.png").read_bytes(), (root / self.REPO_PNG / "Alpha.png").read_bytes())
            anchors = (root / self.ANCHORS).read_bytes()
            self.assertEqual((root / "preview" / "DollArtAnchors.g.cs.txt").read_bytes(), anchors)
            self.assertIn(ex.GENERATED_HEADER, anchors.decode("utf-8"))

    def test_only_limits_the_repository_pngs_and_the_anchors_cover_what_has_landed(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            ex.write_outputs(self.fake_exporter(), root / "preview", write_repo=True, root=root, only=["Beta"])
            self.assertEqual([self.REPO_PNG + "Beta.png"],
                             [w for w in written_files(root) if w.startswith(self.REPO_PNG)])
            anchors = (root / self.ANCHORS).read_text(encoding="utf-8")
            self.assertIn("class Beta", anchors)
            self.assertNotIn("class Alpha", anchors)
            # the preview copy always covers everything
            self.assertIn("class Alpha", (root / "preview" / "DollArtAnchors.g.cs.txt").read_text(encoding="utf-8"))
            # a later weapon lands with a bare name taking its _L rung; the earlier art stays in the anchors
            ex.write_outputs(self.fake_exporter(), root / "preview", write_repo=True, root=root, only=["Alpha"])
            self.assertEqual([self.REPO_PNG + n for n in ("Alpha.png", "Alpha_L.png", "Beta.png")],
                             [w for w in written_files(root) if w.startswith(self.REPO_PNG)])
            anchors = (root / self.ANCHORS).read_text(encoding="utf-8")
            for name in ("Alpha", "Alpha_L", "Beta"):
                self.assertIn(f"class {name}\n", anchors)

    def test_a_bad_only_writes_nothing(self):
        for kwargs in ({"write_repo": True, "only": ["Gamma"]}, {"write_repo": True, "only": ["AlphaCheck"]},
                       {"write_repo": False, "only": ["Alpha"]}):
            with tempfile.TemporaryDirectory() as folder, self.subTest(**kwargs):
                root = Path(folder)
                with self.assertRaises(ValueError):
                    ex.write_outputs(self.fake_exporter(), root / "preview", root=root, **kwargs)
                self.assertEqual([], written_files(root))


@unittest.skipUnless(HAVE_TOOLS, "numpy, scipy and Pillow are local asset-tool dependencies")
class DeliveryFolderTests(unittest.TestCase):
    def test_find_delivery_and_load_both_require_the_manifest(self):
        with tempfile.TemporaryDirectory() as folder:
            bare = Path(folder)
            self.assertFalse(ex.is_delivery(bare))
            with mock.patch.dict(os.environ, {ex.DELIVERY_ENV: str(bare / "missing")}):
                self.assertIsNone(ex.find_delivery())
            with mock.patch.dict(os.environ, {ex.DELIVERY_ENV: str(bare)}):
                self.assertIsNone(ex.find_delivery())  # no manifest.json: not a delivery, and no fallback
            with self.assertRaises(FileNotFoundError):
                ex.Exporter(bare).load()
            (bare / "manifest.json").write_text("{}", encoding="utf-8")
            self.assertTrue(ex.is_delivery(bare))
            with mock.patch.dict(os.environ, {ex.DELIVERY_ENV: str(bare)}):
                self.assertEqual(bare, ex.find_delivery())
            with self.assertRaises(ValueError):  # a manifest without recommendations cannot check the pins
                ex.Exporter(bare).load()


@unittest.skipUnless(HAVE_TOOLS and ex.find_delivery() is not None, "the doll-weapons delivery is not on this machine")
class DeliveryDryRunTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.exporter = ex.Exporter(ex.find_delivery()).run()
        cls.folder = tempfile.TemporaryDirectory()
        cls.report = ex.write_outputs(cls.exporter, Path(cls.folder.name))

    @classmethod
    def tearDownClass(cls):
        cls.folder.cleanup()

    def test_every_pick_is_pinned_and_every_sheet_has_its_objects(self):
        self.assertEqual(21, len(self.report["inputs"]))
        for key, sheet in self.report["sheets"].items():
            self.assertEqual(ex.SHEETS[key].count, len(sheet["objects"]), key)
            self.assertGreaterEqual(sheet["pitch"]["dot_px"], 3.0)

    def test_claws_gun_and_rungs(self):
        outputs = self.report["outputs"]
        for name in ("ClawOpen", "ClawRake", "ClawClench", "ClawThrust"):
            self.assertEqual(2, outputs[name]["k"])
            self.assertEqual(1, outputs[name + "_L"]["k"])
            self.assertEqual(6, len(outputs[name]["anchors"]["beads"]), name)
        self.assertEqual(3, outputs["MeridianGun"]["k"])
        self.assertEqual(list(ex.PART_ORDER), outputs["MeridianParts"]["anchors"]["parts"])
        self.assertEqual(outputs["MeridianGun"]["png_size"], outputs["MeridianBare"]["png_size"])
        self.assertIn("WitnessBlade_L", outputs)

    def reductions(self):
        """(label, entry, reduction record) of every output and every strip frame."""
        for name, entry in self.report["outputs"].items():
            if "reduction" in entry:
                yield name, entry, entry["reduction"]
            for i, frame in enumerate(entry.get("frames_info", [])):
                yield f"{name}#{i}", frame, frame["reduction"]

    def test_no_pitch_sits_at_the_search_ceiling(self):
        for key, sheet in self.report["sheets"].items():
            self.assertFalse(sheet["pitch"]["at_search_ceiling"], key)
        # DW04B's dot is a little over 16 px, which the old 16 px ceiling cut off
        self.assertAlmostEqual(16.68, self.report["sheets"]["DW04B"]["pitch"]["dot_px"], delta=0.2)
        self.assertEqual([], [w for w in self.report["warnings"] if "search ceiling" in w])

    def test_no_object_needs_the_median_cut_fallback(self):
        seen = list(self.reductions())
        self.assertGreater(len(seen), 30)
        self.assertEqual([], [name for name, _, record in seen if "fallback" in record])
        self.assertEqual([], [w for w in self.report["warnings"] if "median-cut fallback" in w])
        self.assertTrue(all(output.image is None for output in self.exporter.outputs))

    def test_outer_boundary_ink_stays_high_for_k_up_to_3(self):
        checked = [(name, record["ink_boundary_share"]) for name, entry, record in self.reductions()
                   if isinstance(entry.get("k"), int) and entry["k"] <= 3]
        self.assertGreater(len(checked), 30)
        for name, share in checked:
            with self.subTest(name=name):
                self.assertGreaterEqual(share, INK_BOUNDARY_FLOOR)

    def test_a_claw_pose_with_fewer_than_five_tips_is_warned(self):
        counts = {}
        for name in ("ClawOpen", "ClawRake", "ClawClench", "ClawThrust"):
            tips = len(self.report["outputs"][name]["anchors"]["tips"])
            counts[name] = tips
            warned = any(w.startswith(f"{name}: found {tips} talon tips, expected {ex.TALONS}") for w in self.report["warnings"])
            self.assertEqual(tips < ex.TALONS, warned, name)
            self.assertEqual(tips, len(self.report["outputs"][name + "_L"]["anchors"]["tips"]), name)
        self.assertEqual(ex.TALONS, max(counts.values()))
        self.assertIn("angular rank", self.report["anchor_rules"]["Claw*.tips"])

    def test_repository_writes_need_write_repo(self):
        runtime = sorted(o.name for o in self.exporter.outputs if o.runtime)
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            ex.write_outputs(self.exporter, root / "preview", root=root)
            self.assertEqual([], [w for w in written_files(root) if not w.startswith("preview/")])
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            ex.write_outputs(self.exporter, root / "preview", write_repo=True, root=root)
            repo = [w for w in written_files(root) if not w.startswith("preview/")]
            expected = [f"{ex.TEXTURE_REL.as_posix()}/{name}.png" for name in runtime] + [ex.ANCHORS_REL.as_posix()]
            self.assertEqual(sorted(expected), repo)
            self.assertEqual((root / "preview" / "DollArtAnchors.g.cs.txt").read_bytes(), (root / ex.ANCHORS_REL).read_bytes())
            self.assertNotIn("MeridianAssembledCheck", " ".join(repo))

    def test_written_files_match_the_report(self):
        folder = Path(self.folder.name)
        for name, entry in self.report["outputs"].items():
            with Image.open(folder / f"{name}.png") as image:
                self.assertEqual(entry["png_size"], list(image.size), name)
            if entry["runtime"]:
                self.assertTrue(entry["path"].startswith("Assets/Textures/Items/DollWeapons/"))
        cs = (folder / "DollArtAnchors.g.cs.txt").read_text(encoding="utf-8")
        self.assertIn(ex.GENERATED_HEADER, cs)
        self.assertNotIn("\r", cs)
        self.assertIsNone(PERSONAL_PATH.search((folder / "report.json").read_text(encoding="utf-8")))


if __name__ == "__main__":
    unittest.main()
